<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE note [
<!ELEMENT note (to, from, Sbj, msg)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT Sbj (#PCDATA)>
<!ELEMENT msg (#PCDATA)>
]>
<note>
 <to>Владислав</to>
 <from>Подобед</from>
 <Sbj>23.01.2021</Sbj>
 <msg>БГТУ ФИТ ПОИТ-6 1-КУРС</msg>
</note>